services:
  angular-app:
    build: .
    container_name: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules  
    command: sh -c "ng serve --host 0.0.0.0 --poll 2000"
